In [1]:
# Frederic Röhder
# 3101179
# Application of Accelerators WS 23/24
# Ex01 / task 11

In [2]:
import numpy as np

In [3]:
# definition of function to multiply two matrices
def matrix_op_multiply(A,B):
  C = A*B
  return C
  print(C)

In [4]:
#creation of two randomly filled 3x3 matrices
A = np.random.rand(3,3)
B = np.random.rand(3,3)

#output for input matrices
print("The first random matrix is: \n", A,"\n")
print("The second random matrix is: \n", B,"\n")

#call for multiplication function
C = matrix_op_multiply(A,B)

#output of result
print("The result of the multiplication of the two matrices is: \n", C)

The first random matrix is: 
 [[0.3329583  0.88548465 0.49466335]
 [0.54452307 0.61522434 0.5989576 ]
 [0.77400801 0.25182007 0.2213513 ]]
The second random matrix is: 
 [[0.65164203 0.80743131 0.3751778 ]
 [0.67008208 0.25964685 0.6872709 ]
 [0.63504936 0.05307841 0.37310251]]
The result of the multiplication of the two matrices is: 
 [[0.21696962 0.71496803 0.18558671]
 [0.36487515 0.15974107 0.41164612]
 [0.49153329 0.01336621 0.08258673]]
